### ISSUE TITLE
Documentation Review

### ISSUE THREAD

**Issue by mitchellreiss** [chuckkainrath/discord-clone-project#2]
# User Stories
- [x] Add more detail to Servers and Channels (Current "so" statements are the same. How are they different? Explain their relationship between the two entities to the user.) 
- [x] Live Chat the reason you are doing this is: So users can get new messages loaded to the page in realtime without having to refresh

Note: _So statements should be less about personally what you like in a feature and why you design it, but more about how will this function. When refining your user stories keep in mind that these will drive your kanban board issues and should describe how the function will work in terms of the UI/UX for you to easily reference when coding._

# DB Design
- [x] Add screenshot of DB design inline with the wiki markdown instead of linking out to an external link

**Comment by TylerRuby0821** [comment]
Thanks Mitchell, will hop on that today!

**Comment by Joemanf** [comment]
Everything should be fixed!

**Comment by TylerRuby0821** [comment]
Going to close the issue, if you see anything else Mitchell, feel free to open up more and we will knock them out!
